/* Week 1 / Ex1 — manual kernel bring-up.
 *
 * Only this file (and the task files you add) belong to you.
 * Do NOT edit anything under Drivers/ or the CubeMX-generated main.c except the
 * single call to app_main() from inside main().
 *
 * Native FreeRTOS API only. cmsis_os.h is forbidden.
 */
#include "FreeRTOS.h"
#include "task.h"

#include "main.h"     /* HAL + CubeMX GPIO defines from template/ */
#include "params.h"   /* generated by tools/gen_params.py */

/* TODO 1: build the GPIO port/pin pair for PA<BLINK_GPIO_PIN>.
 *         Hint: GPIO_PIN_0 .. GPIO_PIN_15 are bit masks, not indices. */

/* TODO 2: implement the bring-up task.
 *         - toggle the pin
 *         - block for BLINK_PERIOD_MS using vTaskDelay()
 *         - the task must never return */
static void bringup_task(void *argument)
{
    (void)argument;

    for (;;) {
        /* TODO */
    }
}

void app_main(void)
{
    /* TODO 3: create bringup_task with stack BRINGUP_STACK_WORDS and a priority
     *         you can justify. Check the return value — do not ignore it. */

    /* TODO 4: start the scheduler. */

    /* Reaching this point means the scheduler returned: out of heap, or the
     * handlers in TODO 5 were never mapped. Trap here so it is visible. */
    for (;;) {
    }
}

/* TODO 5: nothing to write here, but write the answer in REPORT.md:
 *         which three exception handlers does the ARM_CM3 port take over,
 *         where are they currently defined in template/, and what did the
 *         linker say before you resolved the clash? */
